server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          enviroment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          group: groupA
      binder: defaultRabbit
      # default-binder: rabbit
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db2019?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  instance:
    instance-id: receive-8803.com
    prefer-ip-address: true
    # eureka客户端向服务器端服务器端发送心跳的时间间隔，默认30秒
    lease-renewal-interval-in-seconds: 1
    # eureka服务端收到最后一次心跳等待时间上线，默认90秒，超时剔除
    lease-expiration-duration-in-seconds: 2
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: true
    # false表示自己就是注册中心，我的职责就是维护实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

