server:
  port: 7001
spring:
  application:
    name: cloud-eureka
eureka:
  instance:
    hostname: eureka7001.com
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，我的职责就是维护实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 集群指向其他eureka
      defaultZone: http://eureka7002.com:7002/eureka/
      # 单机指向自己
      # defaultZone: http://eureka7001.com:7001/eureka/
  server:
    # 关闭自我保护机制，默认为true（开启）
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
