server:
  port: 8004
spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db2019?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  cloud:
    zookeeper:
      connect-string: 39.98.68.111:2181,39.98.68.111:2182,39.98.68.111:2183


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不用在实体类加上@TableLogic注解)
      logic-delete-field: flag

knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: 123456
  production: false