server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh             # 路由id
          # uri: http://localhost:8001    # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service    # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**      # 断言，路径相匹配的进行路由

        - id: payment_routh2             # 路由id
          # uri: http://localhost:8001    # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service    # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**      # 断言，路径相匹配的进行路由
#            - After=2020-12-09T11:29:00.381+08:00[Asia/Shanghai]
#            - Cookie=username, ykm
#            - Header=X-Request-Id, \d+
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db2019?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

eureka:
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
    # eureka客户端向服务器端服务器端发送心跳的时间间隔，默认30秒
    lease-renewal-interval-in-seconds: 1
    # eureka服务端收到最后一次心跳等待时间上线，默认90秒，超时剔除
    lease-expiration-duration-in-seconds: 2
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: true
    # false表示自己就是注册中心，我的职责就是维护实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
